#ifndef WEB_INTERFACE_H
#define WEB_INTERFACE_H

// Página HTML
const char HTML_BODY[] =
    "<html><head><meta charset='UTF-8' name='viewport' content='width=device-width,initial-scale=1'><title>Estacao Meteorologica</title>"
    "<style>"
    "body{font-family:Arial,sans-serif;margin:10px;background:#f8f9fa;color:#333;}"
    "h2{text-align:center;color:#2c3e50;margin:15px 0;}"
    ".container{max-width:600px;margin:0 auto;}"
    ".card{background:#fff;margin:8px 0;padding:12px;border-radius:8px;box-shadow:0 2px 4px rgba(0,0,0,0.1);}"
    ".row{display:flex;align-items:center;margin:8px 0;}"
    ".label{font-weight:bold;min-width:60px;color:#34495e;}"
    ".value{font-size:18px;font-weight:bold;min-width:80px;text-align:right;}"
    ".chart{flex:1;margin-left:15px;height:20px;background:#ecf0f1;border-radius:10px;overflow:hidden;position:relative;}"
    ".bar{height:100%;border-radius:10px;transition:width 0.5s ease;position:relative;}"
    ".bar::after{content:attr(data-value);position:absolute;right:5px;top:50%;transform:translateY(-50%);font-size:10px;color:#fff;text-shadow:1px 1px 1px rgba(0,0,0,0.5);}"
    ".temp{background:linear-gradient(90deg,#27ae60,#f39c12,#e74c3c);}"
    ".humid{background:linear-gradient(90deg,#3498db,#2ecc71);}"
    ".press{background:linear-gradient(90deg,#9b59b6,#3498db);}"
    ".alt{background:linear-gradient(90deg,#8b4513,#27ae60);}"
    ".status{padding:4px 12px;border-radius:12px;color:#fff;font-size:12px;font-weight:bold;}"
    ".online{background:#27ae60;}"
    ".offline{background:#e74c3c;}"
    ".footer{text-align:center;margin-top:20px;font-size:12px;color:#7f8c8d;}"
    ".setting-group{border:1px solid #eee;padding:10px;border-radius:5px;margin-bottom:10px;}"
    ".setting-group h4{margin-top:0;margin-bottom:8px;color:#2c3e50;}"
    ".setting-group input{width:80px;padding:5px;margin:0 5px;border:1px solid #ccc;border-radius:4px;}"
    ".setting-group .label{min-width:unset;font-weight:normal;}"
    ".setting-group button{background:#3498db;color:#fff;border:none;padding:8px 15px;border-radius:5px;cursor:pointer;width:100%;margin-top:10px;}"
    ".setting-group button:active{background:#2980b9;}"
    "@media (max-width:480px){"
    ".row{flex-direction:column;align-items:flex-start;}"
    ".chart{width:100%;min-width:120px;min-height:20px;height:20px;margin:8px 0 0 0;flex-basis:100%;}"
    ".bar{min-height:20px;height:100%;}"
    ".value{text-align:left;margin:4px 0;}"
    ".setting-group input{width:calc(100% - 10px);margin-bottom:5px;}"
    ".setting-group .row{flex-direction:row;justify-content:space-between;}"
    "}"
    "</style>"
    "<script>"
    "function updateData(){"
    "fetch('/d').then(r=>r.json()).then(d=>{"
    "document.getElementById('temp-val').textContent=d.t.toFixed(1)+'°C';"
    "document.getElementById('humid-val').textContent=d.h.toFixed(1)+'%';"
    "document.getElementById('press-val').textContent=d.p.toFixed(1)+' kPa';"
    "document.getElementById('alt-val').textContent=d.a.toFixed(0)+' m';"
    "var tempPct=Math.min(Math.max(((d.t+40)/125)*100,0),100);"
    "var humidPct=Math.min(Math.max(d.h,0),100);"
    "var pressPct=Math.min(Math.max((d.p-95)*10,0),100);"
    "var altPct=Math.min(Math.max(d.a/20,0),100);"
    "document.getElementById('temp-bar').style.width=tempPct+'%';"
    "document.getElementById('humid-bar').style.width=humidPct+'%';"
    "document.getElementById('press-bar').style.width=pressPct+'%';"
    "document.getElementById('alt-bar').style.width=altPct+'%';"
    "document.getElementById('temp-bar').setAttribute('data-value',tempPct.toFixed(0)+'%');"
    "document.getElementById('humid-bar').setAttribute('data-value',humidPct.toFixed(0)+'%');"
    "document.getElementById('press-bar').setAttribute('data-value',pressPct.toFixed(0)+'%');"
    "document.getElementById('alt-bar').setAttribute('data-value',altPct.toFixed(0)+'%');"
    "}).catch(e=>{"
    "console.log('Erro:',e);"
    "document.getElementById('status').textContent='Offline';"
    "document.getElementById('status').className='status offline';"
    "});"
    "}"
    "function saveSettings(){"
    "var tOff = document.getElementById('temp-offset').value;"
    "var hOff = document.getElementById('humid-offset').value;"
    "var pOff = document.getElementById('press-offset').value;"
    "var aOff = document.getElementById('alt-offset').value;"
    "var url = '/set_config?toff='+tOff+"
    "'&hoff='+hOff+"
    "'&poff='+pOff+"
    "'&aoff='+aOff;"
    "fetch(url).then(r=>r.text()).then(d=>{"
    "document.getElementById('settings-status').textContent='Configurações salvas!';"
    "setTimeout(()=>document.getElementById('settings-status').textContent='',3000);"
    "}).catch(e=>{"
    "console.log('Erro ao salvar:',e);"
    "document.getElementById('settings-status').textContent='Erro ao salvar!';"
    "});"
    "}"
    "setInterval(updateData,1000);"
    "updateData();"
    "</script>"
    "</head><body>"
    "<div class='container'>"
    "<h2>🌤️ Estação Meteorológica</h2>"
    "<div class='card'>"
    "<div style='text-align:center;margin-bottom:10px;'>"
    "<span id='status' class='status online'>Online</span>"
    "</div>"
    "</div>"
    "<div class='card'>"
    "<div class='row'>"
    "<span class='label'>🌡️ Temp:</span>"
    "<span class='value' id='temp-val'>--°C</span>"
    "<div class='chart'><div id='temp-bar' class='bar temp' data-value='0%'></div></div>"
    "</div>"
    "<div class='row'>"
    "<span class='label'>💧 Umid:</span>"
    "<span class='value' id='humid-val'>--%</span>"
    "<div class='chart'><div id='humid-bar' class='bar humid' data-value='0%'></div></div>"
    "</div>"
    "<div class='row'>"
    "<span class='label'>🌪️ Pres:</span>"
    "<span class='value' id='press-val'>-- kPa</span>"
    "<div class='chart'><div id='press-bar' class='bar press' data-value='0%'></div></div>"
    "</div>"
    "<div class='row'>"
    "<span class='label'>⛰️ Alt:</span>"
    "<span class='value' id='alt-val'>-- m</span>"
    "<div class='chart'><div id='alt-bar' class='bar alt' data-value='0%'></div></div>"
    "</div>"
    "</div>"
    // Seção de Configurações
    "<div class='card'>"
    "<h3>⚙️ Calibração de Offset</h3>"
    "<div class='setting-group'>"
    "<h4>Temperatura (°C)</h4>"
    "<div class='row'>"
    "<span class='label'>Offset:</span><input type='number' id='temp-offset' value='0.0' step='0.1'>"
    "</div>"
    "</div>"
    "<div class='setting-group'>"
    "<h4>Umidade (%)</h4>"
    "<div class='row'>"
    "<span class='label'>Offset:</span><input type='number' id='humid-offset' value='0.0' step='0.1'>"
    "</div>"
    "</div>"
    "<div class='setting-group'>"
    "<h4>Pressão (Pa)</h4>"
    "<div class='row'>"
    "<span class='label'>Offset:</span><input type='number' id='press-offset' value='0.0' step='0.1'>"
    "</div>"
    "</div>"
    "<div class='setting-group'>"
    "<h4>Altitude (m)</h4>"
    "<div class='row'>"
    "<span class='label'>Offset:</span><input type='number' id='alt-offset' value='0.0' step='0.1'>"
    "</div>"
    "</div>"
    "<button onclick='saveSettings()'>Salvar Offsets</button>"
    "<p id='settings-status' style='text-align:center;font-size:12px;margin-top:10px;'></p>"
    "</div>"
    "<div class='footer'>"
    "</div>"
    "</div>"
    "</body></html>";

#endif // WEB_INTERFACE_H